import {BUCKET,SUPABASE_KEY,SUPABASE_URL,getContent,requireAdmin,ApiError,json,failure,rest,headers} from '@/lib/server';
import {entrySchema,settingsSchema} from '@/lib/validation';
export const dynamic='force-dynamic';
async function paramsOf(c:any){return (await c.params).action as string[]}
async function mediaRows(){return await rest('lb_media?select=id,name,mime,size,created&order=created.desc')||[]}
async function accessRows(){return await rest('lb_administrators?select=email&order=email.asc')||[]}
async function objectUpload(id:string,file:File,mime:string){const res=await fetch(`${SUPABASE_URL}/storage/v1/object/${BUCKET}/${id}`,{method:'POST',headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${SUPABASE_KEY}`,'Content-Type':mime,'x-upsert':'false'},body:await file.arrayBuffer()});if(!res.ok)throw new Error(await res.text())}
async function objectDelete(id:string){const res=await fetch(`${SUPABASE_URL}/storage/v1/object/${BUCKET}/${id}`,{method:'DELETE',headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${SUPABASE_KEY}`}});if(!res.ok&&res.status!==404)throw new Error(await res.text())}
export async function GET(req:Request,c:any){try{await requireAdmin(req);const [action]=await paramsOf(c);if(action==='content')return json(await getContent(true));if(action==='access')return json(await accessRows());if(action==='media')return json(await mediaRows());throw new ApiError('Página não encontrada.',404)}catch(e){return failure(e)}}
export async function POST(req:Request,c:any){try{await requireAdmin(req,true);const [action,id]=await paramsOf(c);
if(action==='upload'){if(Number(req.headers.get('content-length'))>12*1024*1024)throw new ApiError('A fotografia deve ter no máximo 10 MB.',413);const form=await req.formData();const file=form.get('file');if(!(file instanceof File)||!file.size)throw new ApiError('Selecione uma fotografia.');if(file.size>10*1024*1024)throw new ApiError('A fotografia deve ter no máximo 10 MB.',413);const bytes=new Uint8Array(await file.arrayBuffer());const jpeg=bytes[0]===255&&bytes[1]===216&&bytes[2]===255;const png=bytes[0]===137&&bytes[1]===80&&bytes[2]===78&&bytes[3]===71&&bytes[4]===13&&bytes[5]===10&&bytes[6]===26&&bytes[7]===10;const webp=String.fromCharCode(...bytes.slice(0,4))==='RIFF'&&String.fromCharCode(...bytes.slice(8,12))==='WEBP';const mime=jpeg?'image/jpeg':png?'image/png':webp?'image/webp':'';if(!mime||mime!==file.type)throw new ApiError('Arquivo inválido. Envie uma fotografia JPG, JPEG, PNG ou WebP.');const key=crypto.randomUUID();await objectUpload(key,file,mime);try{await rest('lb_media',{method:'POST',headers:{...headers(),Prefer:'return=minimal'},body:JSON.stringify({id:key,name:file.name.slice(0,250),mime,size:file.size,created:new Date().toISOString()})})}catch(e){await objectDelete(key);throw e}return json({id:key,url:`/api/media/${key}`,alt:'',fit:'contain',x:50,y:50})}
const raw=await req.text();if(raw.length>1800000)throw new ApiError('Conteúdo muito grande para salvar de uma vez.',413);let data:any;try{data=JSON.parse(raw)}catch{throw new ApiError('Os dados não puderam ser lidos. Tente novamente.')}
if(action==='entry'){const parsed=entrySchema.safeParse(data);if(!parsed.success)throw new ApiError(parsed.error.issues.map(x=>x.message).join(' '));const e=parsed.data;if(e.categoryId){const cats=await rest(`lb_categories?id=eq.${encodeURIComponent(e.categoryId)}&select=id`);if(!cats?.length)throw new ApiError('Selecione uma categoria existente.')}for(const p of e.images){const m=await rest(`lb_media?id=eq.${encodeURIComponent(p.id)}&select=id`);if(!m?.length)throw new ApiError('Uma fotografia não está disponível. Envie-a novamente.')}const rows=await rest(`lb_entries?id=eq.${encodeURIComponent(e.id)}&select=revision`);const row=rows?.[0];if(row&&row.revision!==e.revision)throw new ApiError('Este item foi alterado em outra sessão. Copie suas alterações e recarregue antes de salvar.',409);if(!row){const payload={id:e.id,kind:e.kind,slug:e.slug,category_id:e.categoryId||null,status:e.status,hidden:e.hidden,sort:e.order,data:e,revision:1};await rest('lb_entries',{method:'POST',headers:{...headers(),Prefer:'return=minimal'},body:JSON.stringify(payload)});return json({...e,revision:1})}const payload={kind:e.kind,slug:e.slug,category_id:e.categoryId||null,status:e.status,hidden:e.hidden,sort:e.order,data:e,revision:e.revision+1};const updated=await rest(`lb_entries?id=eq.${encodeURIComponent(e.id)}&revision=eq.${e.revision}`,{method:'PATCH',headers:{...headers(),Prefer:'return=representation'},body:JSON.stringify(payload)});if(!updated?.length)throw new ApiError('Este item foi alterado em outra sessão. Recarregue antes de salvar.',409);return json({...e,revision:e.revision+1})}
if(action==='settings'){const parsed=settingsSchema.safeParse(data);if(!parsed.success)throw new ApiError(parsed.error.issues.map(x=>x.message).join(' '));const s=parsed.data;const rows=await rest('lb_settings?id=eq.site&select=revision');const row=rows?.[0];if(!row){if(s.revision!==0)throw new ApiError('Atualize a página antes de salvar.',409);await rest('lb_settings',{method:'POST',headers:{...headers(),Prefer:'return=minimal'},body:JSON.stringify({id:'site',data:s,revision:1})});return json({...s,revision:1})}if(row.revision!==s.revision)throw new ApiError('As configurações foram alteradas em outra sessão. Copie suas alterações e recarregue.',409);const updated=await rest(`lb_settings?id=eq.site&revision=eq.${s.revision}`,{method:'PATCH',headers:{...headers(),Prefer:'return=representation'},body:JSON.stringify({data:s,revision:s.revision+1})});if(!updated?.length)throw new ApiError('As configurações foram alteradas em outra sessão. Copie suas alterações e recarregue.',409);return json({...s,revision:s.revision+1})}
if(action==='category'){if(typeof data.id!=='string'||typeof data.name!=='string'||!data.name.trim()||data.name.length>150||!Number.isFinite(data.order))throw new ApiError('Informe o nome da categoria.');await rest('lb_categories?on_conflict=id',{method:'POST',headers:{...headers(),Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({id:data.id,name:data.name.trim(),sort:data.order})});return json(data)}
if(action==='reorder'){if(!['entries','categories'].includes(data.type)||!Array.isArray(data.ids)||!data.ids.every((x:any)=>typeof x==='string'))throw new ApiError('Organização inválida.');for(let i=0;i<data.ids.length;i++){const table=data.type==='entries'?'lb_entries':'lb_categories';if(data.type==='entries'){const rows=await rest(`${table}?id=eq.${encodeURIComponent(data.ids[i])}&select=revision`);await rest(`${table}?id=eq.${encodeURIComponent(data.ids[i])}`,{method:'PATCH',headers:headers(),body:JSON.stringify({sort:i,revision:(rows?.[0]?.revision||0)+1})})}else await rest(`${table}?id=eq.${encodeURIComponent(data.ids[i])}`,{method:'PATCH',headers:headers(),body:JSON.stringify({sort:i})})}return json({ok:true})}
if(action==='access'){const email=String(data.email||'').trim().toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))throw new ApiError('Informe um e-mail válido.');await rest('lb_administrators?on_conflict=email',{method:'POST',headers:{...headers(),Prefer:'resolution=ignore-duplicates,return=minimal'},body:JSON.stringify({email})});return json({ok:true})}
if(action==='delete-category'){const target=String(data.target||'');if(target===id)throw new ApiError('Escolha outra categoria.');if(target){const cats=await rest(`lb_categories?id=eq.${encodeURIComponent(target)}&select=id`);if(!cats?.length)throw new ApiError('Categoria de destino inexistente.')}await rest(`lb_entries?category_id=eq.${encodeURIComponent(id||'')}`,{method:'PATCH',headers:headers(),body:JSON.stringify({category_id:target||null})});await rest(`lb_categories?id=eq.${encodeURIComponent(id||'')}`,{method:'DELETE'});return json({ok:true})}
throw new ApiError('Ação não encontrada.',404)}catch(e){return failure(e)}}
export async function DELETE(req:Request,c:any){try{const user=await requireAdmin(req,true);const [action,id]=await paramsOf(c);if(action==='entry'){await rest(`lb_entries?id=eq.${encodeURIComponent(id||'')}`,{method:'DELETE'});return json({ok:true})}if(action==='media'){const [entries,settings]=await Promise.all([rest(`lb_entries?select=id,data`),rest('lb_settings?id=eq.site&select=data')]);const used=[...(entries||[]),...(settings||[])].some((r:any)=>JSON.stringify(r.data||{}).includes(String(id)));if(used)throw new ApiError('Esta fotografia está em uso. Remova-a dos conteúdos e salve antes de excluí-la.',409);await objectDelete(String(id));await rest(`lb_media?id=eq.${encodeURIComponent(id||'')}`,{method:'DELETE'});return json({ok:true})}if(action==='access'){const email=decodeURIComponent(id||'');if(email===user.email.toLowerCase())throw new ApiError('O acesso principal não pode ser removido aqui.');await rest(`lb_administrators?email=eq.${encodeURIComponent(email)}`,{method:'DELETE'});return json({ok:true})}throw new ApiError('Ação não encontrada.',404)}catch(e){return failure(e)}}
