export type Photo = {id:string;url:string;alt:string;fit:'contain'|'cover';x:number;y:number};
export type Entry = {id:string;kind:'product'|'class';name:string;slug:string;description:string;categoryId:string;status:'draft'|'published';hidden:boolean;featured:boolean;order:number;price:string;priceMode:'show'|'hide'|'consult';availability:string;images:Photo[];details:Record<string,string>;custom:{name:string;value:string}[];revision:number};
export type Category={id:string;name:string;order:number};
export type Section={id:string;page:string;type:string;title:string;eyebrow:string;body:string;images:Photo[];buttonLabel:string;buttonHref:string;visible:boolean;layout:string;mobileLayout:string;align:string;background:string;spacing:string};
export type Settings={brand:string;creator:string;tagline:string;logo:Photo[];favicon:Photo[];whatsapp:string;instagram:string;address:string;footer:string;theme:{background:string;surface:string;text:string;muted:string;accent:string;buttonText:string;line:string;headingFont:string;bodyFont:string;radius:string;width:string};nav:{id:string;label:string;href:string;visible:boolean}[];sections:Section[];pages:Record<string,{title:string;description:string}>;revision:number};
export type Content={settings:Settings;categories:Category[];entries:Entry[]};
export const notice='Para pedir produtos, consulte a vendedora pelo WhatsApp ou Instagram. Valores, disponibilidade e condições são confirmados diretamente com ela.';
export const productFields:Record<string,string>={colors:'Cores',dimensions:'Dimensões',materials:'Materiais',technique:'Técnica',finish:'Acabamento',care:'Cuidados'};
export const classFields:Record<string,string>={audience:'Público',level:'Nível de experiência',techniques:'Técnicas ensinadas',format:'Formato',location:'Local',schedule:'Horários',duration:'Duração',materials:'Materiais'};
export const sectionTypes:Record<string,string>={hero:'Banner principal',text:'Texto',image:'Fotografia',split:'Imagem e texto',gallery:'Galeria',products:'Produtos em destaque',classes:'Aulas e oficinas',contact:'Chamada de contato'};
export const fonts:Record<string,string>={editorial:'Georgia, "Times New Roman", serif',classic:'"Palatino Linotype", Palatino, Georgia, serif',modern:'Arial, Helvetica, sans-serif'};
export function section(id:string,page:string,type:string,title:string,body='',buttonLabel='',buttonHref=''):Section{return {id,page,type,title,body,eyebrow:'',images:[],buttonLabel,buttonHref,visible:true,layout:'image-right',mobileLayout:'text-first',align:'left',background:'',spacing:'normal'}}
export const defaults:Settings={revision:0,brand:'LB studio',creator:'Rosilene Brunhara',tagline:'Cerâmica · Arte · Encontro',logo:[],favicon:[],whatsapp:'',instagram:'',address:'',footer:'Cerâmica, histórias e o prazer de criar.',theme:{background:'#f8f5ef',surface:'#ede7dc',text:'#3e3027',muted:'#716253',accent:'#624630',buttonText:'#ffffff',line:'#d9d0c4',headingFont:'editorial',bodyFont:'modern',radius:'2',width:'1240'},nav:[{id:'home',label:'Início',href:'/',visible:true},{id:'catalog',label:'Catálogo',href:'/catalogo',visible:true},{id:'about',label:'Sobre mim',href:'/sobre',visible:true},{id:'classes',label:'Aulas',href:'/aulas',visible:true},{id:'contact',label:'Contato',href:'/contato',visible:true}],pages:{catalog:{title:'Peças para fazer parte\nda sua história.',description:'Conheça as cerâmicas da LB studio.'},about:{title:'Rosilene\nBrunhara.',description:'Criadora da LB studio'},classes:{title:'Um encontro com\na sua criatividade.',description:'Aulas e oficinas de cerâmica com Rosilene Brunhara.'},contact:{title:'Toda boa história\ncomeça com uma conversa.',description:'Vamos conversar sobre uma peça ou sobre as aulas?'}},sections:[{...section('hero','home','hero','A beleza de\nsentir o tempo.','Cerâmica, arte e um convite para olhar os detalhes.','Explorar catálogo','/catalogo'),eyebrow:'LB STUDIO · ROSILENE BRUNHARA'},section('featured','home','products','Peças, com presença.','','Explorar catálogo','/catalogo'),{...section('creator','home','split','Por trás da cerâmica,\numa história.','Conheça Rosilene Brunhara, criadora da LB studio.','Conhecer minha história','/sobre'),eyebrow:'SOBRE MIM'}, {...section('lessons','home','split','Um convite para\ncriar com as mãos.','Conheça as aulas e oficinas da LB studio.','Saiba mais sobre as aulas','/aulas'),eyebrow:'AULAS & OFICINAS',layout:'image-left',background:'#ede7dc'},section('contact-home','home','contact','Vamos conversar?'),{...section('history','about','text','Minha história'),visible:false},{...section('process','about','split','Meu processo criativo'),visible:false},{...section('inspiration','about','gallery','Inspirações e ateliê'),visible:false},section('about-classes','about','classes','Aprender, experimentar, criar.','Conheça as aulas e oficinas da LB studio.','Saiba mais sobre as aulas','/aulas')]};
export const blankEntry=(kind:Entry['kind']):Entry=>({id:uuid(),kind,name:'',slug:'',description:'',categoryId:'',status:'draft',hidden:false,featured:false,order:Date.now(),price:'',priceMode:'consult',availability:'',images:[],details:{},custom:[],revision:0});
export function slugify(s:string){return s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}
export function priceLabel(e:Entry){if(e.priceMode==='hide')return '';if(e.priceMode==='consult')return 'Preço sob consulta';return e.price?Number(e.price).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}):''}
export function entryPath(e:Entry){return `/${e.kind==='product'?'pecas':'aulas'}/${e.slug||slugify(e.name)}`}
export function instagramUrl(value:string){if(!value)return '';try{const u=new URL(value);if(u.protocol==='https:'&&['instagram.com','www.instagram.com','ig.me','www.ig.me'].includes(u.hostname))return u.href}catch{}return ''}
export function whatsappUrl(s:Settings,e?:Entry,origin=''){const digits=s.whatsapp.replace(/\D/g,'');if(!/^\d{10,15}$/.test(digits))return '';const msg=e?`Olá! Gostaria de saber mais sobre ${e.kind==='product'?'a peça':'a aula'} “${e.name}”. ${origin}${entryPath(e)}`:`Olá! Gostaria de saber mais sobre a ${s.brand}.`;return `https://wa.me/${digits}?text=${encodeURIComponent(msg)}`}

export function uuid(){if(typeof crypto.randomUUID==="function")return crypto.randomUUID();const b=crypto.getRandomValues(new Uint8Array(16));b[6]=(b[6]&15)|64;b[8]=(b[8]&63)|128;const h=Array.from(b,x=>x.toString(16).padStart(2,"0")).join("");return `${h.slice(0,8)}-${h.slice(8,12)}-${h.slice(12,16)}-${h.slice(16,20)}-${h.slice(20)}`}
