import {z} from 'zod';
const short=z.string().max(300);
const photo=z.object({id:z.string().uuid(),url:z.string().regex(/^\/api\/media\/[a-f0-9-]{36}$/),alt:z.string().max(500),fit:z.enum(['contain','cover']),x:z.number().min(0).max(100),y:z.number().min(0).max(100)});
export const entrySchema=z.object({id:z.string().uuid(),kind:z.enum(['product','class']),name:short.trim().min(1,'Informe o nome.'),slug:z.string().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/,'Use letras minúsculas, números e hífens no endereço.').max(180),description:z.string().max(50000),categoryId:z.string().max(80),status:z.enum(['draft','published']),hidden:z.boolean(),featured:z.boolean(),order:z.number(),price:z.string().refine(s=>s===''||(/^\d+(\.\d{1,2})?$/.test(s)&&Number(s)<=999999999),'Informe um preço válido em reais.'),priceMode:z.enum(['show','hide','consult']),availability:z.enum(['','Disponível','Sob encomenda','Indisponível']),images:z.array(photo),details:z.record(z.string().max(100),z.string().max(10000)),custom:z.array(z.object({name:short,value:z.string().max(10000)})),revision:z.number().int().nonnegative()}).superRefine((e,c)=>{if(e.status==='published'&&(!e.images.length||!e.description.trim()))c.addIssue({code:'custom',message:'Para publicar, adicione uma fotografia e uma descrição.'});if(e.priceMode==='show'&&!e.price)c.addIssue({code:'custom',message:'Informe o preço ou escolha “Preço sob consulta”.'})});
const hex=z.string().regex(/^#[0-9a-fA-F]{6}$/);
const safeHref=z.string().refine(s=>!s||(/^\/(?!\/)[^\s\\]*$/.test(s)&&!s.startsWith('/api/'))||/^https:\/\//.test(s),'Use um caminho iniciado por / ou um endereço https://.');
const sectionSchema=z.object({id:short,page:z.enum(['home','catalog','about','classes','contact']),type:z.enum(['hero','text','image','split','gallery','products','classes','contact']),title:short,eyebrow:short,body:z.string().max(50000),images:z.array(photo),buttonLabel:short,buttonHref:safeHref,visible:z.boolean(),layout:z.enum(['image-left','image-right']),mobileLayout:z.enum(['image-first','text-first']),align:z.enum(['left','center']),background:z.union([hex,z.literal('')]),spacing:z.enum(['compact','normal','generous'])});
export const settingsSchema=z.object({brand:short.trim().min(1,'Informe o nome da marca.'),creator:short,tagline:short,logo:z.array(photo),favicon:z.array(photo),whatsapp:z.string().refine(s=>!s||/^\d{10,15}$/.test(s.replace(/\D/g,'')),'Informe WhatsApp com código do país e DDD (10 a 15 dígitos).'),instagram:z.string().refine(s=>{if(!s)return true;try{const u=new URL(s);return u.protocol==='https:'&&['instagram.com','www.instagram.com','ig.me','www.ig.me'].includes(u.hostname)}catch{return false}},'Informe um endereço https:// válido do Instagram.'),address:z.string().max(2000),footer:z.string().max(3000),theme:z.object({background:hex,surface:hex,text:hex,muted:hex,accent:hex,buttonText:hex,line:hex,headingFont:z.enum(['editorial','classic','modern']),bodyFont:z.enum(['editorial','classic','modern']),radius:z.enum(['0','2','8','20']),width:z.enum(['1100','1240','1440'])}),nav:z.array(z.object({id:short,label:short.trim().min(1),href:safeHref,visible:z.boolean()})),sections:z.array(sectionSchema),pages:z.record(z.string(),z.object({title:short,description:z.string().max(3000)})),revision:z.number().int().nonnegative()});
export function checked<T>(schema:z.ZodType<T>,data:unknown){const r=schema.safeParse(data);if(!r.success)throw new Error(r.error.issues.map(x=>x.message).join(' '));return r.data}
